/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.7.1/userguide/building_java_projects.html
 */

buildscript {
}

plugins {
    java
    id("com.github.johnrengelman.shadow") version "4.0.1" apply false
}

subprojects {
    apply(plugin = "java")

    repositories {
        // Use JCenter for resolving dependencies.
        mavenCentral()
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}




